### ISSUE TITLE
missing class BaseJob in Airflow 2

### ISSUE THREAD

**Issue by xhuyvn** [teamclairvoyant/airflow-maintenance-dags#102]
Hi

I am using Airflow 2, when use airflow-db-cleanup.py it shows an error when combining code:
missing BaseJob in airflow.jobs class 
===> from airflow.jobs import BaseJob

I removed that, and it run well. But nothing happens, Dagrun, DagInstance ... still the same. On Airflow UI still show alot row.

**Comment by xhuyvn** [comment]
Hi
I had fixed it by using beblow
from airflow.jobs.base_job import BaseJob

**Comment by diman82** [comment]
Got the same problem when upgrading to airflow version 2.6.3
Solution is to change to:
`from airflow.jobs.job import Job`

**Comment by sthakkar-rdc** [comment]
@diman82 did you mean below ?

```
from airflow.jobs.job import BaseJob
```

Update 1 : above import didn't work. Maybe `BaseJob` is deprecated. I'll try above suggestion.

Update 2 : Above import `from airflow.jobs.job import Job` worked
