### ISSUE TITLE
Airflow 2.0.2 renames the last_scheduler_run column (used in db cleanup job)

### ISSUE THREAD

**Issue by swiffer** [teamclairvoyant/airflow-maintenance-dags#110]
https://github.com/apache/airflow/commit/c2a0cb958835d0cecd90f82311e2aa8b1bbd22a0#diff-fd7ce54d2146064dd83398f84ab648a0ffad06e941a76c53c82901257204f779

**Comment by prakshalj0512** [comment]
Is this fix compatible with Airflow 1.x?
