### ISSUE TITLE
DagModel cleanup fails due to dependency record in the DagTag table 

### ISSUE THREAD

**Issue by vadipo** [teamclairvoyant/airflow-maintenance-dags#111]
DagTag is another model in the database that maps dag-tags to dag ids, there is foreign key relationship between dag _id column to DagModel 

class DagTag(Base):
    """
    A tag name per dag, to allow quick filtering in the DAG view.
    """
    __tablename__ = "dag_tag"
    name = Column(String(100), primary_key=True)
    dag_id = Column(String(ID_LEN), ForeignKey('dag.dag_id'), primary_key=True)

when cleaning the DagModel need to take care of the DagTag model as well

**Comment by yuzeh** [comment]
Is there a workaround here?

**Comment by vadipo** [comment]
yeah.. you can add a little code block that fixes the issue, 
I didn't had time to contribute it back..

**Comment by vadipo** [comment]
I opened a PR, take a look 
https://github.com/teamclairvoyant/airflow-maintenance-dags/pull/116
