### ISSUE TITLE
Keep at least one DAG Run for active DAG

### ISSUE THREAD

**Issue by hsun-cnnxty** [teamclairvoyant/airflow-maintenance-dags#18]
We configure the maintenance DAG to keep 90-day history which works well. Recently we added a new DAG which has to backfill the data from the beginning of the year.  However, when maintenance DAG runs, it just removes all DAG Runs older than 90 days, including the new DAG.  This caused the new DAG to rerun from the beginning again.  Seems the maintenance DAG should keep an least one DAG Run if a DAG is still active.

**Comment by rssanders3** [comment]
Similar fix made in PR: https://github.com/teamclairvoyant/airflow-maintenance-dags/pull/33
