### ISSUE TITLE
ERROR - naive datetime is disallowed 

### ISSUE THREAD

**Issue by sunnykrGupta** [teamclairvoyant/airflow-maintenance-dags#24]
After running DAG, i faced the below error to all set_downsteam instances. Altough, `print_configuration` was unaffected, so it ran successfully. After tracking the error in python libs, I found it is being caught here. https://github.com/apache/incubator-airflow/blob/4083a8f5217e9ca7a5c83a3eaaaf403dd367a90c/airflow/utils/sqlalchemy.py#L153

It looks like non-naive timestamp is not allowed beyond AF(1.10), not sure about previous version.

Environment : 
- AF - v1.10.0

----

`[2018-11-28 17:54:15,124] {models.py:1736} ERROR - (builtins.ValueError) naive datetime is disallowed [SQL: 'SELECT task_instance.try_number AS task_instance_try_number, task_instance.task_id AS task_instance_task_id, task_instance.dag_id AS task_instance_dag_id, task_instance.execution_date AS task_instance_execution_date, task_instance.start_date AS task_instance_start_date, task_instance.end_date AS task_instance_end_date, task_instance.duration AS task_instance_duration, task_instance.state AS task_instance_state, task_instance.max_tries AS task_instance_max_tries, task_instance.hostname AS task_instance_hostname, task_instance.unixname AS task_instance_unixname, task_instance.job_id AS task_instance_job_id, task_instance.pool AS task_instance_pool, task_instance.queue AS task_instance_queue, task_instance.priority_weight AS task_instance_priority_weight, task_instance.operator AS task_instance_operator, task_instance.queued_dttm AS task_instance_queued_dttm, task_instance.pid AS task_instance_pid, task_instance.executor_config AS task_instance_executor_config \nFROM task_instance \nWHERE task_instance.execution_date <= %s'] [parameters: [{}]]
Traceback (most recent call last):
  File "/home/daemonsl/airflow/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1116, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/home/daemonsl/airflow/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 623, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/home/daemonsl/airflow/venv/lib/python3.5/site-packages/sqlalchemy/sql/type_api.py", line 1078, in process
    return process_param(value, dialect)
  File "/home/daemonsl/airflow/venv/lib/python3.5/site-packages/airflow/utils/sqlalchemy.py", line 156, in process_bind_param
    raise ValueError('naive datetime is disallowed')
ValueError: naive datetime is disallowed`

**Comment by rssanders3** [comment]
Change made as apart of #30
