### ISSUE TITLE
Multiple Worker Machine Log Clearnup

### ISSUE THREAD

**Issue by weizhao-wish** [teamclairvoyant/airflow-maintenance-dags#26]
I believe the task in a DAG is send to worker randomly by scheduler. How do you make sure that all worker machine get logs cleaned?

In the code I just see a loop of NUMBER_OF_WORKERS, but this don't guarantee that each worker will run the task and get log cleaned up.

**Comment by rssanders3** [comment]
Hello @weizhao-wish, Airflow doesn't currently have the capability of targeting a specific task to run on a specific Airflow worker. So therefore in general we can't guarantee that the tasks will be executed on all the workers in one dag run and therefore cleanup all the logs. The goal of the NUMBER_OF_WORKERS variable is to try and increase the odds of the tasks getting executed on all the machines, or at least executed once every couple of days. 

Another potential solution is to have the cleanup process run as CRON jobs on the actual machine, but this might require a bit more work if you want to support some of the things Airflow brings to the table:
- Alerting
- Visualization
- Configurability
- Distribution
- etc
