### ISSUE TITLE
child_process_log_directory logs?

### ISSUE THREAD

**Issue by marklit** [teamclairvoyant/airflow-maintenance-dags#27]
Any chance you could add the ``child_process_log_directory`` to the list of logs cleaned up?

https://github.com/apache/incubator-airflow/blob/71129cd2100f102b7efc45e085da607ffd579018/UPDATING.md#child_process_log_directory

**Comment by rssanders3** [comment]
Fixed in https://github.com/teamclairvoyant/airflow-maintenance-dags/pull/32 which was recently merged.

**Comment by marklit** [comment]
Fantastic, thank you.
