### ISSUE TITLE
'max_db_entry_age_in_days' from Variable causes a TypeError: bad operand type for unary -: 'str'

### ISSUE THREAD

**Issue by fmacelw** [teamclairvoyant/airflow-maintenance-dags#28]
When the `max_db_entry_age_in_days` is retrieved from `Variable.get` https://github.com/teamclairvoyant/airflow-maintenance-dags/blob/5f9ab63cf7e97b2d4e92afa93763ebea7e69abd6/db-cleanup/airflow-db-cleanup.py#L24 is then returned as a string.

This leads to the following error:

```
  File "/usr/local/airflow/dags/maintenance/airflow-db-cleanup.py", line 66, in print_configuration_function
    max_date = datetime.now(tz=tzinfo) + timedelta(-max_db_entry_age_in_days)
TypeError: bad operand type for unary -: 'str'
```

Wrapping it with an `int()` seems to solve the problem:
```python
DEFAULT_MAX_DB_ENTRY_AGE_IN_DAYS = int(Variable.get("max_db_entry_age_in_days", 30))
```

**Comment by rssanders3** [comment]
Change made as apart of https://github.com/teamclairvoyant/airflow-maintenance-dags/pull/30
