### ISSUE TITLE
airflow-db-cleanup should be retrieving only the primary key column to avoid out of memory

### ISSUE THREAD

**Issue by fmacelw** [teamclairvoyant/airflow-maintenance-dags#29]
When running the airflow db cleanup dag, it loads the full rows in memory as per

https://github.com/teamclairvoyant/airflow-maintenance-dags/blob/5f9ab63cf7e97b2d4e92afa93763ebea7e69abd6/db-cleanup/airflow-db-cleanup.py#L101-L103

Translating into this (postgres) query, e.g.
```sql
SELECT xcom.id AS xcom_id, xcom.key AS xcom_key, xcom.value AS xcom_value, xcom.timestamp AS xcom_timestamp, xcom.execution_date AS xcom_execution_date, xcom.task_id AS xcom_task_id, xcom.dag_id AS xcom_dag_id 
	FROM xcom 
	WHERE xcom.execution_date <= '2018-11-24T16:48:30.861484+00:00'::timestamptz
```

For `xcom` tables with large values being passed around, this quickly leads to out of memory.

As the purpose of the `session.query` is to only read rows to be deleted, it would be better to only load enough information to subsequently delete the rows (and any other essential info, e.g. timestamp). 

I'm not a python / sqlalchemy expert, but I can see that something like [load_only](https://docs.sqlalchemy.org/en/latest/orm/loading_columns.html#load-only-cols) is available for this

**Comment by rssanders3** [comment]
Similar fix made in PR: https://github.com/teamclairvoyant/airflow-maintenance-dags/pull/33
