### ISSUE TITLE
Bulk deletes

### ISSUE THREAD

**Issue by sudev** [teamclairvoyant/airflow-maintenance-dags#35]
Delete operation is happening inside a for loop for every object that we get from the select query here. 

```sql
SELECT log.id AS log_id, log.dttm AS log_dttm FROM log WHERE log.dttm <= %s
```

I have no idea on how the sqlAlchemy works, but from the I can infer that we are trying to delete item by item followed by a commit call. 

```python 
for entry in entries_to_delete:
        session.delete(entry)
        session.commit()
```

But why dont we do a bulk delete? 

```sql 
--- A sql version will look like this.
DELETE from log where log.dttm < "max-time-to-retain-we-get-from-select-query"
```

If someone can help me understand the feasibility of this method, I would like to do a PR for this.

Why can't we do a `query.delete()` ?

**Comment by sudhakar-nallam** [comment]
@sudev Thanks for pointing this. This was taken care in #36
