### ISSUE TITLE
directory won't be cleanup

### ISSUE THREAD

**Issue by petersunbag** [teamclairvoyant/airflow-maintenance-dags#38]
`log_cleanup_file_op.set_downstream(log_cleanup_dir_op)`
 you cleanup file first, which changes the  directory modify time to now, and the
 `find /home/xiaoju/airflow/logs/*/* -type d -empty -mtime +30` will return nothing

**Comment by Max821214** [comment]
When you delete the log, the modification time of the directory will also change.

**Comment by sudhakar-nallam** [comment]
Thank you @petersunbag for reporting this issue. This is taken care in #39
