### ISSUE TITLE
airflow-log-cleanup dag stays in running state with tasks in None state

### ISSUE THREAD

**Issue by Shailesh-Pandey** [teamclairvoyant/airflow-maintenance-dags#43]
I have setup the global variables and then triggered the dag to see how it performs but I'm getting the tasks in None state as shown below:
![image](https://user-images.githubusercontent.com/46490790/61862953-51d5ed00-aeec-11e9-8304-c14324918149.png)

Details:
Airflow =1.10.1
Celery = 4.3.0
Python = 2.7.12
Postgres = 11.3
Ubuntu = 16.04
Rabbitmq-server = 3.7.15

**Comment by rssanders3** [comment]
@Shailesh-Pandey is this happening with any of your other DAGs? Do you see any ERRORs in the Worker logs that might indicate a problem?

**Comment by Shailesh-Pandey** [comment]
> @Shailesh-Pandey is this happening with any of your other DAGs? Do you see any ERRORs in the Worker logs that might indicate a problem?
Thanks for the response:
1. The other dags are working fine without any issues.
2. Regarding the logs. I do not see any logs regarding this dag in the logs folder. Are Worker logs saved anywhere else?

**Comment by Shailesh-Pandey** [comment]
Sorry for bugging. I don't know the root cause but these steps solved the issue.
1. Changed the group and user of dag to root.
2. Turned the dag on instead of triggering manually.
