### ISSUE TITLE
Cannot import settings 

### ISSUE THREAD

**Issue by joseangel-sc** [teamclairvoyant/airflow-maintenance-dags#47]
So, I believe this is only in the newest version of Airflow 

```from airflow.models import settings``` for the cleanup DAG

Throws this ```ImportError: cannot import name 'settings' from 'airflow.models' (/usr/local/lib/python3.7/site-packages/airflow/models/__init__.py)``` 

So, apparently, there are not `settings`? Not sure yet if this is truly an issue with this cleanup dag or is something else with the configuration

**Comment by rssanders3** [comment]
@joseangel-sc I actually committed a fix for this issue this morning. Can you check the latest?

**Comment by joseangel-sc** [comment]
@rssanders3 yep! can confirm it works with the new imports, thanks!
