### ISSUE TITLE
Says: Only works with the CeleryExecutor, sorry

### ISSUE THREAD

**Issue by joaolcorreia** [teamclairvoyant/airflow-maintenance-dags#50]
I'm trying to run two dags using Dask

- airflow-kill-halted-tasks
- airflow-log-cleanup

and getting: `Only works with the CeleryExecutor, sorry`

Any tips?

Thanks
Joao

**Comment by sudhakar-nallam** [comment]
@joaolcorreia Can you please share more details. 
1. Airflow version?
2. RDBMS version?
3. SQL client version?
4. OS platform
5. Any erros logs / stacktraces

**Comment by rssanders3** [comment]
@joaolcorreia are you still encountering this issue?
