### ISSUE TITLE
disk space not changed after running this cleanup dag

### ISSUE THREAD

**Issue by qiangbo** [teamclairvoyant/airflow-maintenance-dags#55]
Hi, sorry if this sounds stupid... after running this dag as is, I have not noticed any changes in the disk space in the airflow server. Am I doing anything wrong?

**Comment by sudhakar-nallam** [comment]
@qiangbo Can you share more details. 
How much old log data you have? By default log-cleanup dag is set to remove the files that are 30 days old or older.

**Comment by rssanders3** [comment]
@qiangbo can you confirm if you're still having an issue?
