### ISSUE TITLE
airflow-log-cleanup task may fail if BASE_LOG_FOLDER is parent dir of CHILD_PROCESS_LOG_DIRECTORY

### ISSUE THREAD

**Issue by ChenyuanZ** [teamclairvoyant/airflow-maintenance-dags#61]
If `BASE_LOG_FOLDER` is the parent dir of `CHILD_PROCESS_LOG_DIRECTORY`, https://github.com/teamclairvoyant/airflow-maintenance-dags/blob/master/log-cleanup/airflow-log-cleanup.py#L76-L84 can fail because both tasks will try to delete the same file.

**Comment by rssanders3** [comment]
Hello @ChenyuanZ, since the delete operation is done sequentially, the CHILD_PROCESS_LOG_DIRECTORYs files won't be tried to deleted until after the content of the BASE_LOG_FODLER. So they shouldn't be trying to delete at the same time. Are you seeing an issue like this?

**Comment by rssanders3** [comment]
@ChenyuanZ are you seeing issues with this?
