### ISSUE TITLE
airflow_log_cleanup DAG creating DUPLICATE task instances when there a change in Code and Deploy

### ISSUE THREAD

**Issue by ajay999aj** [teamclairvoyant/airflow-maintenance-dags#64]
Hi,

In airlfow_log_cleanup DAG ,i have made some changes and Deployed them in my Environment but i there are Duplicate tasks created in the DAG with a name extension of _0 & _1

How can we avoid this Duplicate tasks? i tried executing the airflow_db_clean DAG but still it doesn't work.

Thanks

**Comment by prakshalj0512** [comment]
Those tasks are being created as per the number of workers set by the following variable in the code: `NUMBER_OF_WORKERS`. It attempts to remove logs from each worker by executing the task that many numbers of times, hoping to execute the cleanup process on that node once.
