### ISSUE TITLE
add session.commit() after delete for airflow 1.9

### ISSUE THREAD

**Issue by ocorbier** [teamclairvoyant/airflow-maintenance-dags#7]
Hi, 
Nice job, i appreciate these dags !! 

With airflow 1.9, the session alchemy is instanced with autocommit=false
In settings.py : 
   _Session = scoped_session(
         sessionmaker(autocommit=False, autoflush=False, bind=engine))_

I add a _session.commit()_ after the loop  _session.delete(entry)_ in the script airflow-db-cleanup.py, and it's work !!!

**Comment by Hasan-J** [comment]
Hello,
I've included the changes for this issue. I can PR if you want to check them out.

**Comment by rssanders3** [comment]
Change made as apart of https://github.com/teamclairvoyant/airflow-maintenance-dags/pull/30
