### ISSUE TITLE
celery_taskmeta and celery_tasksetmeta tables

### ISSUE THREAD

**Issue by royt-via** [teamclairvoyant/airflow-maintenance-dags#75]
Does the current cleanup deal with `celery_taskmeta` and `celery_tasksetmeta` tables?
If not, how can I add it to the `DATABASE_OBJECTS` array? there isn't a corresponding airflow.models for it
Thanks!

**Comment by rssanders3** [comment]
Hello @royt-via, 

Currently, the db-cleanup process does not clean up these tables. You can probably accomplish this by updating the `DATABASE_OBJECTS` array in the DAG to include the DB model. 

I see there is a db model object here:
https://docs.celeryproject.org/en/stable/_modules/celery/backends/database/models.html

So you could import the necessary model and include it in the array:

`from celery.backends.database.models import Task, TaskSet`
...
```
    {
        "airflow_db_model": Task,
        "age_check_column": Task.date_done,
        "keep_last": False,
        "keep_last_filters": None,
        "keep_last_group_by": None
    },
    {
        "airflow_db_model": TaskSet,
        "age_check_column": TaskSet.date_done,
        "keep_last": False,
        "keep_last_filters": None,
        "keep_last_group_by": None
    },
```

Let me know if this resolves your issue.

Thanks,
Robert Sanders

**Comment by rssanders3** [comment]
Now available in the current version of the db-cleanup DAG:
https://github.com/teamclairvoyant/airflow-maintenance-dags/pull/80
