### ISSUE TITLE
clean-db broken unless you install celerity

### ISSUE THREAD

**Issue by Daniel-SBD** [teamclairvoyant/airflow-maintenance-dags#79]
There are many different airflow deployments. 
The strongest trend now goes with kubernetes executor. There are simpler deployments for small environments too where LocalExecutor feels convenient. 
Both deployments can not take advantaje of your, previously magnificent, [db cleanup script](https://github.com/teamclairvoyant/airflow-maintenance-dags/tree/master/db-cleanup), because it requires the celerity module.

**Comment by rssanders3** [comment]
Fix now available in the latest PR:
https://github.com/teamclairvoyant/airflow-maintenance-dags/pull/80
