### ISSUE TITLE
airflow-db-cleanup - RenderedTaskInstanceFields could not be found

### ISSUE THREAD

**Issue by gflores1023** [teamclairvoyant/airflow-maintenance-dags#83]
Airflow had trouble parsing this airflow-db-cleanup dag. RenderedTaskInstanceFields could not be found.

I don't know what it is and so I just removed it in the `from airflow.models import` and also from `DATABASE_OBJECTS`.

Airflow v1.10.4 using the sequential operator

**Comment by prakshalj0512** [comment]
Hi Gabe,
We're aware of this issue and I'm working on it right now. Will keep you posted and let you know once the fix is merged.
