### ISSUE TITLE
Had to cast execution_date as Text to get the LIKE clause working

### ISSUE THREAD

**Issue by roomnoise** [teamclairvoyant/airflow-maintenance-dags#9]
In order to get `kill-halted-tasks` to work, I had to cast `execution_date` as text.  

ex: `CAST(DagRun.execution_date as TEXT)`

Otherwise, I get the following error:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) operator does not exist: timestamp without time zone ~~ unknown
Subtask: LINE 3: ...n.dag_id = 'example-dag' AND dag_run.execution_date LIKE '2018...
```

Happy to submit a PR. Just wanted to give a heads-up first.

**Comment by Sanyorke-Han** [comment]
I met the same problem when upgrade to airflow 1.10.07 with postgresql 10.  I temporary change to:
        dag_run = session.query(DagRun).filter(
            and_(
                DagRun.dag_id == process["airflow_dag_id"],
                **DagRun.execution_date >= execution_date_to_search_for**,
            )
        ).first()
it looks not report error, but not sure if this correct in business. because it uses SQLAlchemy backend, I don't how to cast timestamp field to text via python code to SQLAlchemy.

**Comment by rssanders3** [comment]
Change made as apart of https://github.com/teamclairvoyant/airflow-maintenance-dags/pull/30
